version: '3.3'
services:
  db:
    image: mysql:5.7
    command: --max_allowed_packet=67108864
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    volumes:
        - ./database/mysql:/var/lib/mysql
    networks:
      - back
    restart: always

  django:
    build: .
    command: bash -c "python3 daemon.py & python3 manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/code

    depends_on:
      - db
    networks:
      - back
      - front
    restart: always

  nginx:
    image: nginx:1.21.4
    depends_on:
      - django
      - phpmyadmin
      - db
    ports:
      - 80:80
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - front
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    networks:
      - front
      - back
    restart: always

networks:
  front:
    external: true
  back:
    external: true