# Generated by Django 3.2.9 on 2022-01-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('idDoc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('idResidente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('doc', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=65)),
                ('telefono2', models.CharField(blank=True, max_length=65, null=True)),
                ('email', models.CharField(max_length=65)),
                ('departamento', models.CharField(max_length=6)),
                ('propietario', models.BooleanField(default=False)),
                ('tipoDoc', models.ForeignKey(db_column='idDoc', on_delete=django.db.models.deletion.DO_NOTHING, related_name='residente', to='residentes.tipodoc')),
            ],
        ),
    ]
