# Generated by Django 3.2.9 on 2022-01-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='residente',
            table='residentes_lista',
        ),
    ]
