# Generated by Django 3.2.9 on 2022-01-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_alter_residente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('idTag', models.AutoField(primary_key=True, serialize=False)),
                ('nroTag', models.BigIntegerField()),
                ('codSeguridad', models.BigIntegerField()),
                ('residente', models.ForeignKey(db_column='idResidente', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='residentes.residente')),
            ],
        ),
    ]
