# Generated by Django 3.2.9 on 2022-01-02 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edificios', '0001_initial'),
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuertaAbierta',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('resuelta', models.BooleanField(default=False)),
                ('observaciones', models.CharField(max_length=300)),
                ('edificio', models.ForeignKey(db_column='idEdificio', on_delete=django.db.models.deletion.CASCADE, related_name='puertaAbierta', to='edificios.edificio')),
                ('equipo', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, related_name='puertaAbiertaEquipo', to='edificios.equiposacr')),
                ('residente', models.ForeignKey(db_column='idResidente', on_delete=django.db.models.deletion.CASCADE, related_name='puertaAbiertaRedt', to='residentes.residente')),
                ('responsable', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, related_name='puertaAbiertaResp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
