# Generated by Django 3.2.9 on 2022-01-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificios', '0001_initial'),
        ('residentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('idReg', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('voltaje', models.FloatField()),
                ('estado', models.CharField(max_length=25)),
                ('edificio', models.ForeignKey(db_column='idEdificio', on_delete=django.db.models.deletion.CASCADE, related_name='bateria', to='edificios.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('idReg', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('edificio', models.ForeignKey(db_column='idEdificio', on_delete=django.db.models.deletion.CASCADE, related_name='registrosEdificio', to='edificios.edificio')),
                ('residente', models.ForeignKey(db_column='idResidente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='registros', to='residentes.residente')),
            ],
        ),
    ]
