# Generated by Django 3.2.9 on 2022-01-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_tag'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceso',
            name='tag',
            field=models.ForeignKey(db_column='idTag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='registrosTag', to='residentes.tag'),
        ),
    ]
