"""
Django settings for sacrApi project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = True
PRODUCTION = False

CORS_ORIGIN_ALLOW_ALL = True
#CORS_ORIGIN_WHITELIST = ['']
# CORS_ALLOW_CREDENTIALS = True

ALLOWED_HOSTS = ['http://localhost', 'localhost']