"""
Django settings for sacrApi project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
TEMPLATE_DEBUG = False
PRODUCTION = True

ALLOWED_HOSTS = ['sacr.com.ar']

XS_SHARING_ALLOWED_ORIGINS = 'http://localhost'

CORS_ORIGIN_ALLOW_ALL = False
#CORS_ORIGIN_WHITELIST = ['']
CORS_ALLOW_CREDENTIALS = True

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sacr',
        'USER': 'sacrsys',
        'PASSWORD':	'ADg03JoAJI6gW0m6',
        'HOST': 'db',
        'PORT': '3306',
    }
}