# Generated by Django 3.2.9 on 2022-01-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('idEdificio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('calle', models.CharField(max_length=45)),
                ('numero', models.IntegerField(null=True)),
                ('barrio', models.CharField(max_length=45)),
                ('ciudad', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('idResidente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('apellido', models.CharField(max_length=75)),
                ('tipoDoc', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('LC', 'Libreta Cívica'), ('LE', 'Libreta de Enrolamiento')], max_length=10)),
                ('doc', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=65)),
                ('telefono2', models.CharField(blank=True, max_length=65, null=True)),
                ('email', models.CharField(max_length=65)),
                ('departamento', models.CharField(max_length=6)),
                ('propietario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoSACR',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('nroSerie', models.CharField(max_length=60)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
                ('mac', models.CharField(blank=True, max_length=45, null=True)),
                ('edificio', models.ForeignKey(db_column='idEdificio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipoSACR', to='edificios.edificio')),
                ('usuario', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='equipoSACR_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
